server:
  port: 8088
spring:
  application:
    name: @project.name@
  profiles:
    active: @profiles.active@
  web:
    resources:
      static-locations: classpath:/dist
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'generator'
      paths-to-match: '/**'
      packages-to-scan: com.vipicu.maker.generator.controller
      
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# orm config
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true

logging:
  config: classpath:logback-delayed.xml